-- INSERT statements for all products
-- Generated automatically from HTML files
-- Run these in your Supabase SQL Editor

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT016',
    'Barro No.2 Side Table',
    'barro-no2-side-table',
    'MAKEMAKE',
    555,
    'Expertly crafted in our San José workshop, the Barro No.2 Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763162160/Barro_No.2_2_nqp8aw.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763162160/Barro_No.2_2_nqp8aw.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763162162/Barro_No.2_1_u13t7a.jpg"]'::jsonb,
    '[{"name":"One Size","price":555,"dimensions":"Ø38 x H50 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"38 cm / 15.0\""},{"label":"Height","value":"50 cm / 19.7\""}]'::jsonb,
    '<p><strong>Handcrafted Clay:</strong> Natural clay, hand-shaped and kiln-baked. Finished with urethane paint and sealed in high-gloss resin for durability. Fragile by nature"”avoid hard impacts.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p>Handle with care. The aluminum base protects against easy chips or cracks, but it''s not foolproof. Clean with a soft, damp cloth. Lift, don''t drag.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted from solid hardwood with distinctive turned legs and a carefully proportioned top. Each piece showcases traditional woodworking techniques.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    '{"color":[{"name":"Crema","color":"#F7EDD4"},{"name":"Sienna","color":"#B85C4F"},{"name":"Dove","color":"#E8E4DF"},{"name":"Camel","color":"#C4A57B"},{"name":"Seagrass","color":"#B8B695"},{"name":"Olive","color":"#5F6E52"},{"name":"Bay","color":"#8A9BA8"},{"name":"Nautical","color":"#3A4D5C"}]}'::jsonb,
    ARRAY['tables', 'side-tables', 'outdoor']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT023',
    'Barro No.4 Side Table',
    'barro-no4-side-table',
    'MAKEMAKE',
    555,
    'Expertly crafted in our San José workshop, the Barro No.4 Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765548139/Barro_No4_2_hwajma.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765548139/Barro_No4_2_hwajma.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765546937/Barro_No4_1_b8jlas.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765548254/Barro_No4_3_ttnyls.jpg"]'::jsonb,
    '[{"name":"One Size","price":555,"dimensions":"Ø38 x H50 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"38 cm / 15.0\""},{"label":"Height","value":"50 cm / 19.7\""}]'::jsonb,
    '<p><strong>Handcrafted Clay:</strong> Natural clay, hand-shaped and kiln-baked. Finished with urethane paint and sealed in high-gloss resin for durability. Fragile by nature"”avoid hard impacts.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p>Handle with care. The aluminum base protects against easy chips or cracks, but it''s not foolproof. Clean with a soft, damp cloth. Lift, don''t drag.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted side table with distinctive character. Each piece showcases careful attention to form and finish.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    '{"color":[{"name":"Crema","color":"#F7EDD4"},{"name":"Sienna","color":"#B85C4F"},{"name":"Dove","color":"#E8E4DF"},{"name":"Camel","color":"#C4A57B"},{"name":"Seagrass","color":"#B8B695"},{"name":"Olive","color":"#5F6E52"},{"name":"Bay","color":"#8A9BA8"},{"name":"Nautical","color":"#3A4D5C"}]}'::jsonb,
    ARRAY['tables', 'side-tables', 'outdoor']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT009',
    'Bloque No.1 Side Table',
    'bloque-no1-side-table',
    'MAKEMAKE',
    400,
    'Expertly crafted in our San José workshop, the Bloque No.1 Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328243/BloqueNo1_1_rhq5tn.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328243/BloqueNo1_1_rhq5tn.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328247/BloqueNo1_2_xf0345.jpg"]'::jsonb,
    '[{"name":"One Size","price":400,"dimensions":"W50 x L50 x H44 cm"}]'::jsonb,
    '[{"label":"Length","value":"50 cm / 19.7\""},{"label":"Width","value":"50 cm / 19.7\""},{"label":"Height","value":"44 cm / 17.3\""}]'::jsonb,
    '<p><strong>High Gloss Lacquered MDF:</strong> Medium-density fiberboard finished with a high-gloss automotive polyurethane paint for a smooth, durable surface.</p>                         <p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>To maintain the lacquer finish, use only a soft, damp cloth for cleaning. Paper towels and abrasive materials should be avoided. Should light scratches occur, they can be carefully buffed out using automotive polish.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Crafted from solid hardwood with clean, geometric forms. The minimalist design showcases the beauty of simple, honest construction.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'DT001',
    'Botella Dining Table',
    'botella-dining-table',
    'MAKEMAKE',
    1700,
    'Expertly crafted in our San José workshop, the Botella Dining Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '8-10 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763322882/Botella_1_mas66x.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763322882/Botella_1_mas66x.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763322885/Botella_2_jlhdfb.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763322882/Botella_3_yccmjx.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763322880/Botella_4_witg1e.jpg"]'::jsonb,
    '[{"name":"One Size","price":1700,"dimensions":"Ø120 x H76 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"120 cm / 47.2\""},{"label":"Height","value":"76 cm / 29.9\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly crafted from premium hardwoods with focus on proportion and joinery. The distinctive base design showcases skilled woodworking.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['tables', 'dining-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'SCH002',
    'Cazo Side Chair',
    'cazo-side-chair',
    'MAKEMAKE',
    900,
    'Expertly crafted in our San José workshop, the Cazo Side Chair embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160798/Cazo_3_zbjkmw.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160798/Cazo_3_zbjkmw.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160803/Cazo_2_ujisnf.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160793/Cazo_1_cdb2a3.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160809/Cazo_4_wvn3um.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328129/Cazo_Detail_2_zxi3ic.jpg"]'::jsonb,
    '[{"name":"One Size","price":900,"dimensions":"W40 x D40 x H80 cm (seat H46cm)"}]'::jsonb,
    '[{"label":"Width","value":"40 cm / 15.7\""},{"label":"Depth","value":"40 cm / 15.7\""},{"label":"Height","value":"80 cm / 31.5\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted from Costa Rican hardwood with careful attention to ergonomics and proportion. The curved seat and supportive back are shaped for comfort.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['seating', 'chairs']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'DK001',
    'Depto. Parsons Desk',
    'depto-parsons-desk',
    'MAKEMAKE',
    1150,
    'Expertly crafted in our San José workshop, the Depto. Parsons Desk embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763156922/Depto.Parsons_1_m6sjxv.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763156922/Depto.Parsons_1_m6sjxv.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763156935/Depto.Parsons_3_jeoxxo.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763156941/Depto.Parsons_2_opyekv.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763156926/Depto.Parsons_4_hd1rjn.jpg"]'::jsonb,
    '[{"name":"Small","price":1150,"dimensions":"W60 x L120 x H78 cm"},{"name":"Large","price":1350,"dimensions":"W60 x L150 x H78 cm"}]'::jsonb,
    '[{"label":"Length","value":"120 cm / 47.2\""},{"label":"Width","value":"60 cm / 23.6\""},{"label":"Height","value":"78 cm / 30.7\""},{"label":"Length","value":"150 cm / 59.1\""},{"label":"Width","value":"60 cm / 23.6\""},{"label":"Height","value":"78 cm / 30.7\""}]'::jsonb,
    '<p><strong>High Gloss Lacquered MDF:</strong> Medium-density fiberboard finished with a high-gloss automotive polyurethane paint for a smooth, durable surface.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>To maintain the lacquer finish, use only a soft, damp cloth for cleaning. Paper towels and abrasive materials should be avoided. Should light scratches occur, they can be carefully buffed out using automotive polish.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Crafted from Costa Rican hardwoods with meticulous attention to joinery and proportion. The desk''s clean lines and honest construction showcase the natural beauty of the wood.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    null,
    ARRAY['storage']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CT004',
    'Dizi Coffee Table',
    'dizi-coffee-table',
    'MAKEMAKE',
    1200,
    'Expertly crafted in our San José workshop, the Dizi Coffee Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160506/Dizi_Coffee_Thumbnail_uzac9u.png',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160506/Dizi_Coffee_Thumbnail_uzac9u.png","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160517/Dizi_Coffee_1_htkjiu.jpg"]'::jsonb,
    '[{"name":"One Size","price":1200,"dimensions":"Ø100 x H38 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"100 cm / 39.4\""},{"label":"Height","value":"38 cm / 15.0\""}]'::jsonb,
    '<p><strong>Local Teak:</strong> Sustainably sourced Costa Rican hardwood with natural resistance to moisture, decay, and insects. Weathers to a silver-grey patina or maintains its golden tone with occasional oiling.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Avoid prolonged direct exposure to rain.</p>',
    '<p>Clean with mild soap and water. Avoid harsh chemicals. Teak naturally silvers over time"”this is normal and does not affect durability. To maintain the original warm tone, apply teak oil 2-3 times per year.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly crafted from sustainably sourced hardwood. The distinctive top design showcases traditional woodworking techniques adapted for contemporary living.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'coffee-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT006',
    'Dizi Side Table',
    'dizi-side-table',
    'MAKEMAKE',
    0,
    'Expertly crafted in our San José workshop, the Dizi Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763159490/Dizi_2_f2fm4g.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763159490/Dizi_2_f2fm4g.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763159671/Dizi_3_w2onnr.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763159481/Dizi_1_mohchl.jpg"]'::jsonb,
    '[{"name":"One Size","price":525,"dimensions":"W40 x L40 x H50 cm"}]'::jsonb,
    '[{"label":"Width","value":"40 cm / 15.7\""},{"label":"Depth","value":"40 cm / 15.7\""},{"label":"Height","value":"50 cm / 19.7\""},{"label":"Width","value":"50 cm / 19.7\""},{"label":"Depth","value":"40 cm / 15.7\""},{"label":"Height","value":"40 cm / 15.7\""}]'::jsonb,
    '<p><strong>Local Teak:</strong> Sustainably sourced Costa Rican hardwood with natural resistance to moisture, decay, and insects. Weathers to a silver-grey patina or maintains its golden tone with occasional oiling.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Avoid prolonged direct exposure to rain.</p>',
    '<p>Clean with mild soap and water. Avoid harsh chemicals. Teak naturally silvers over time"”this is normal and does not affect durability. To maintain the original warm tone, apply teak oil 2-3 times per year.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Hand-carved from solid hardwood with attention to sculptural form. Each piece showcases the natural grain and character of Costa Rican wood.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT027',
    'Filial Side Table',
    'filial-side-table',
    'MAKEMAKE',
    715,
    'Expertly crafted in our San José workshop, the Filial Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '8-10 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765550378/Filial_Side_Table_2_vvaegq.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765550378/Filial_Side_Table_2_vvaegq.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1765550351/Filial_Side_Table_1_oqscfe.jpg"]'::jsonb,
    '[{"name":"One Size","price":715,"dimensions":"Ø50 x H45 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"50 cm / 19.7\""},{"label":"Height","value":"45 cm / 17.7\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Crafted with care by local artisans. Attention to detail and finish ensures each piece is unique.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CH012',
    'Fortuna Chair',
    'fortuna-chair',
    'MAKEMAKE',
    695,
    'Expertly crafted in our San José workshop, the Fortuna Chair embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764017513/Fortuna_1_iiodfx.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764017513/Fortuna_1_iiodfx.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764017513/Fortuna_2_o10t2t.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764017509/Fortuna_3_pkhkuu.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764017508/Fortuna_4_mtvx4t.jpg"]'::jsonb,
    '[{"name":"Single","price":695,"dimensions":"W65 x D75 x H68 cm (seat H44)"},{"name":"Double","price":1350,"dimensions":"W140 x D75 x H68 cm (seat H44)"}]'::jsonb,
    '[{"label":"Width","value":"65 cm / 25.6\""},{"label":"Depth","value":"75 cm / 29.5\""},{"label":"Height","value":"68 cm / 26.8\""},{"label":"Width","value":"140 cm / 55.1\""},{"label":"Depth","value":"75 cm / 29.5\""},{"label":"Height","value":"68 cm / 26.8\""}]'::jsonb,
    '<p><strong>Leather:</strong> Premium leather available in select colors and finishes.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>                         <p><strong>Leather Care:</strong> Regularly dust with a soft, dry cloth or vacuum with an upholstery attachment. For cleaning, lightly dampen a soft cloth with distilled water and gently wipe"”do not leave moisture on the leather. Avoid placing near heat sources or in direct sunlight, which can cause fading and cracking. Leather naturally develops character and patina with age. For stubborn stains, consult a professional leather technician.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted from sustainably sourced hardwood with attention to proportion and comfort. Traditional techniques ensure lasting quality.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    true,
    false,
    null,
    ARRAY['seating', 'chairs']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT001',
    'Globo Side Table',
    'globo-side-table',
    'MAKEMAKE',
    675,
    'Expertly crafted in our San José workshop, the Globo Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763157341/Globo_1_ryehnr.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763157341/Globo_1_ryehnr.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763157352/Globo_2_xhj0g8.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763157345/Globo_3_acndok.jpg"]'::jsonb,
    '[{"name":"One Size","price":675,"dimensions":"Ø46 x H50 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"46 cm / 18.1\""},{"label":"Height","value":"50 cm / 19.7\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Hand-turned from solid Costa Rican hardwood. Each piece is carefully shaped on a lathe, then hand-finished to highlight the wood''s natural grain and character.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'DT012',
    'Gracia Dining Table',
    'gracia-dining-table',
    'MAKEMAKE',
    2850,
    'Expertly crafted in our San José workshop, the Gracia Dining Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328496/Gracia_1_qrexhs.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328496/Gracia_1_qrexhs.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328504/Gracia_Counter_jhvv8a.jpg"]'::jsonb,
    '[{"name":"Long-Standard(H)","price":2850,"dimensions":"W110 x L200 x H76 cm"},{"name":"Small-Standard(H)","price":2380,"dimensions":"W110 x L220 x H76 cm"},{"name":"Small-Counter(H)","price":2380,"dimensions":"W100 x L220 x H92 cm"}]'::jsonb,
    '[{"label":"Length","value":"200 cm / 78.7\""},{"label":"Width","value":"110 cm / 43.3\""},{"label":"Height","value":"76 cm / 29.9\""},{"label":"Length","value":"220 cm / 86.6\""},{"label":"Width","value":"110 cm / 43.3\""},{"label":"Height","value":"76 cm / 29.9\""},{"label":"Length","value":"220 cm / 86.6\""},{"label":"Width","value":"100 cm / 39.4\""},{"label":"Height","value":"92 cm / 36.2\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly crafted from premium Costa Rican hardwoods. The substantial top and carefully proportioned base create a dining table built for gathering.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'dining-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CO001',
    'Hache Console',
    'hache-console',
    'MAKEMAKE',
    2350,
    'Expertly crafted in our San José workshop, the Hache Console embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '8-10 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336801/Hache_Console_3_nzwonn.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336801/Hache_Console_3_nzwonn.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336741/Hache_Console_2.jpg_uzlaqh.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336811/Hache_Console_Vertical_rmu1tz.jpg"]'::jsonb,
    '[{"name":"One Size","price":2350,"dimensions":"W45 x L180 x H80 cm"}]'::jsonb,
    '[{"label":"Length","value":"180 cm / 70.9\""},{"label":"Width","value":"45 cm / 17.7\""},{"label":"Height","value":"80 cm / 31.5\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly crafted console with attention to proportion and detail. Solid construction ensures stability and lasting quality.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['storage']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT004',
    'Half Side Table',
    'half-side-table',
    'MAKEMAKE',
    495,
    'Expertly crafted in our San José workshop, the Half Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328287/Half_1_ghjckm.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328287/Half_1_ghjckm.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328293/Half_2_vikmx2.jpg"]'::jsonb,
    '[{"name":"One Size","price":495,"dimensions":"Ø40 x H48 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"40 cm / 15.7\""},{"label":"Height","value":"48 cm / 18.9\""}]'::jsonb,
    '<p><strong>Handcrafted Clay:</strong> Natural clay, hand-shaped and kiln-baked. Finished with urethane paint and sealed in high-gloss resin for durability. Fragile by nature"”avoid hard impacts.</p>                         <p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>To maintain the lacquer finish, use only a soft, damp cloth for cleaning. Paper towels and abrasive materials should be avoided. Should light scratches occur, they can be carefully buffed out using automotive polish.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly crafted with contrasting materials that create visual interest. Careful joinery ensures structural integrity and lasting beauty.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    '{"color":[{"name":"Crema","color":"#F7EDD4"},{"name":"Sienna","color":"#B85C4F"},{"name":"Dove","color":"#E8E4DF"},{"name":"Camel","color":"#C4A57B"},{"name":"Seagrass","color":"#B8B695"},{"name":"Olive","color":"#5F6E52"},{"name":"Bay","color":"#8A9BA8"},{"name":"Nautical","color":"#3A4D5C"}]}'::jsonb,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CH017',
    'Mano Chair',
    'mano-chair',
    'MAKEMAKE',
    1240,
    'Expertly crafted in our San José workshop, the Mano Chair embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763326218/Mano_Chair_3_pgfyg4.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763326218/Mano_Chair_3_pgfyg4.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763326222/Mano_Chair_4_mi3pgt.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763326217/Mano_Chair_1_kckjvf.jpg"]'::jsonb,
    '[{"name":"One Size","price":1240,"dimensions":"W88 x D92 x H60 cm (seat H42)"}]'::jsonb,
    '[{"label":"Width","value":"88 cm / 34.6\""},{"label":"Depth","value":"92 cm / 36.2\""},{"label":"Height","value":"60 cm / 23.6\""}]'::jsonb,
    '<p><strong>Local Teak:</strong> Sustainably sourced Costa Rican hardwood with natural resistance to moisture, decay, and insects. Weathers to a silver-grey patina or maintains its golden tone with occasional oiling.</p>                         <p><strong>Performance Upholstery:</strong> Exterior-grade fabric designed to resist fading, moisture, and everyday wear. Easy to clean and built for tropical conditions.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Avoid prolonged direct exposure to rain.</p>',
    '<p>Clean with mild soap and water. Avoid harsh chemicals. Teak naturally silvers over time"”this is normal and does not affect durability. To maintain the original warm tone, apply teak oil 2-3 times per year.</p>                         <p><strong>Upholstery:</strong> Brush off loose dirt regularly. Spot clean with mild soap and water. Allow to dry completely. Performance fabric is designed to resist fading and moisture.</p>                         <p><strong>Machine Wash:</strong> For deeper cleaning, removable covers may be machine washed. Close all zippers, machine wash in cold water on the delicate cycle with mild laundry detergent. Air dry completely"”never tumble dry or apply heat. For severe stains, add 1 cup of color-safe oxygen bleach (such as OxiClean) to the wash cycle"”never use chlorine bleach on colored fabrics.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly upholstered in San José with premium fabrics over a solid hardwood frame. Each chair is built for lasting comfort and durability.',
    'all',
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    null,
    ARRAY['seating', 'chairs']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'SO010',
    'Mano Sofa',
    'mano-sofa',
    'MAKEMAKE',
    2255,
    'Expertly crafted in our San José workshop, the Mano Sofa embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763325277/Mano_Sofa_4_d56ugm.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763325277/Mano_Sofa_4_d56ugm.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763325279/Mano_Sofa_1_esswe8.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763325281/Mano_Sofa_2_fgdejn.jpg"]'::jsonb,
    '[{"name":"3-Seater","price":2255,"dimensions":"W215 x D90 x H75 cm (seat H42cm)"},{"name":"4-Seater","price":2955,"dimensions":"W285 x D90 x H75 cm (seat H42cm)"}]'::jsonb,
    '[{"label":"Width","value":"215 cm / 84.6\""},{"label":"Depth","value":"90 cm / 35.4\""},{"label":"Height","value":"75 cm / 29.5\""},{"label":"Width","value":"285 cm / 112.2\""},{"label":"Depth","value":"90 cm / 35.4\""},{"label":"Height","value":"75 cm / 29.5\""}]'::jsonb,
    '<p><strong>Local Teak:</strong> Sustainably sourced Costa Rican hardwood with natural resistance to moisture, decay, and insects. Weathers to a silver-grey patina or maintains its golden tone with occasional oiling.</p>                         <p><strong>Performance Upholstery:</strong> Exterior-grade fabric designed to resist fading, moisture, and everyday wear. Easy to clean and built for tropical conditions.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Avoid prolonged direct exposure to rain.</p>',
    '<p>Clean with mild soap and water. Avoid harsh chemicals. Teak naturally silvers over time"”this is normal and does not affect durability. To maintain the original warm tone, apply teak oil 2-3 times per year.</p>                         <p><strong>Upholstery:</strong> Brush off loose dirt regularly. Spot clean with mild soap and water. Allow to dry completely. Performance fabric is designed to resist fading and moisture.</p>                         <p><strong>Machine Wash:</strong> For deeper cleaning, removable covers may be machine washed. Close all zippers, machine wash in cold water on the delicate cycle with mild laundry detergent. Air dry completely"”never tumble dry or apply heat. For severe stains, add 1 cup of color-safe oxygen bleach (such as OxiClean) to the wash cycle"”never use chlorine bleach on colored fabrics.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Upholstered by skilled artisans in San José. Each frame is built from sustainably sourced hardwood and finished with premium fabrics selected for durability and comfort.',
    'all',
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    null,
    ARRAY['seating', 'sofas']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'DB001',
    'Morfeo Daybed',
    'morfeo-daybed',
    'MAKEMAKE',
    2225,
    'Expertly crafted in our San José workshop, the Morfeo Daybed embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328852/Morfeo_Daybed_Thumbnail_flklnb.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328852/Morfeo_Daybed_Thumbnail_flklnb.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763329754/Morfeo_Daybed_2_dla4nw.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763329750/Morfeo_Daybed_3_fmm256.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763329746/Morfeo_Daybed_4_bv46h2.jpg"]'::jsonb,
    '[{"name":"One Size","price":2225,"dimensions":"W200 x D90 x H62 cm (seat H42)"}]'::jsonb,
    '[{"label":"Width","value":"200 cm / 78.7\""},{"label":"Depth","value":"90 cm / 35.4\""},{"label":"Height","value":"62 cm / 24.4\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                         <p><strong>Performance Upholstery:</strong> Exterior-grade fabric designed to resist fading, moisture, and everyday wear. Easy to clean and built for tropical conditions.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Performance upholstery resists moisture and fading.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly upholstered in San José with premium materials over a solid hardwood frame. Built for comfort and lasting quality.',
    'all',
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    ARRAY['seating', 'daybeds']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'NT001',
    'Morfeo Nightstand',
    'morfeo-nightstand',
    'MAKEMAKE',
    575,
    'Expertly crafted in our San José workshop, the Morfeo Nightstand embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763320553/Morfeo_Nightstand_1_kwaaju.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763320553/Morfeo_Nightstand_1_kwaaju.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763320555/Morfeo_Nightstand_2_vlys30.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763320556/Morfeo_Nighstand_3_kalke4.jpg"]'::jsonb,
    '[{"name":"One Size","price":575,"dimensions":"W50 x L45 x H50 cm"}]'::jsonb,
    '[{"label":"Length","value":"45 cm / 17.7\""},{"label":"Width","value":"50 cm / 19.7\""},{"label":"Height","value":"50 cm / 19.7\""}]'::jsonb,
    '<p><strong>Handcrafted Clay:</strong> Natural clay, hand-shaped and kiln-baked. Finished with urethane paint and sealed in high-gloss resin for durability. Fragile by nature"”avoid hard impacts.</p>                         <p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>To maintain the lacquer finish, use only a soft, damp cloth for cleaning. Paper towels and abrasive materials should be avoided. Should light scratches occur, they can be carefully buffed out using automotive polish.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted from sustainably sourced hardwood with focus on proportion and utility. Drawer construction ensures smooth operation and lasting function.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    '{"color":[{"name":"Crema","color":"#F7EDD4"},{"name":"Sienna","color":"#B85C4F"},{"name":"Dove","color":"#E8E4DF"},{"name":"Camel","color":"#C4A57B"},{"name":"Seagrass","color":"#B8B695"},{"name":"Olive","color":"#5F6E52"},{"name":"Bay","color":"#8A9BA8"},{"name":"Nautical","color":"#3A4D5C"}]}'::jsonb,
    ARRAY['storage']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT020',
    'Pablo Side Table',
    'pablo-side-table',
    'MAKEMAKE',
    475,
    'Expertly crafted in our San José workshop, the Pablo Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328448/Pablo_1_bg9dce.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328448/Pablo_1_bg9dce.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328311/Pablo2_ttwjea.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328315/Pablo3_vmsood.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328318/Pablo4_s6fudp.jpg"]'::jsonb,
    '[{"name":"One Size","price":475,"dimensions":"Ø38 x H50 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"38 cm / 15.0\""},{"label":"Height","value":"50 cm / 19.7\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                         <p><strong>Powder-Coated Steel:</strong> Durable steel finished with weather-resistant powder coating. Available in multiple color options to match our clay and lacquer finishes.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Hand-built from sustainably sourced hardwood with focus on proportion and detail. Each piece is individually finished to highlight the wood''s character.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CH010',
    'Perse Chair',
    'perse-chair',
    'MAKEMAKE',
    815,
    'Expertly crafted in our San José workshop, the Perse Chair embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764016551/Perse_1_oumsfy.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764016551/Perse_1_oumsfy.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764016551/Perse_2_zyitbv.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764016548/Perse_3_towdtx.jpg"]'::jsonb,
    '[{"name":"One Size","price":815,"dimensions":"W75 x D80 x H75 cm (seat H42)"}]'::jsonb,
    '[{"label":"Width","value":"75 cm / 29.5\""},{"label":"Depth","value":"80 cm / 31.5\""},{"label":"Height","value":"75 cm / 29.5\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                         <p><strong>Performance Upholstery:</strong> Exterior-grade fabric designed to resist fading, moisture, and everyday wear. Easy to clean and built for tropical conditions.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Performance upholstery resists moisture and fading.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>                         <p><strong>Machine Wash:</strong> For deeper cleaning, removable covers may be machine washed. Close all zippers, machine wash in cold water on the delicate cycle with mild laundry detergent. Air dry completely"”never tumble dry or apply heat. For severe stains, add 1 cup of color-safe oxygen bleach (such as OxiClean) to the wash cycle"”never use chlorine bleach on colored fabrics.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Hand-built from Costa Rican hardwood with focus on clean lines and honest construction. Each chair showcases careful joinery and finishing.',
    'all',
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    ARRAY['seating', 'chairs']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CT018',
    'Petra Coffee Table',
    'petra-coffee-table',
    'MAKEMAKE',
    0,
    'Expertly crafted in our San José workshop, the Petra Coffee Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160620/Petra_1_fqmndl.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160620/Petra_1_fqmndl.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160614/Petra_2_dg1zyy.jpg"]'::jsonb,
    '[{"name":"One Size","price":1900,"dimensions":"W110 x L110 x H42 cm"}]'::jsonb,
    '[{"label":"Length","value":"110 cm / 43.3\""},{"label":"Width","value":"110 cm / 43.3\""},{"label":"Height","value":"42 cm / 16.5\""}]'::jsonb,
    '<p><strong>High Gloss Lacquered MDF:</strong> Medium-density fiberboard finished with a high-gloss automotive polyurethane paint for a smooth, durable surface.</p>                         <p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>To maintain the lacquer finish, use only a soft, damp cloth for cleaning. Paper towels and abrasive materials should be avoided. Should light scratches occur, they can be carefully buffed out using automotive polish.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Expertly crafted from sustainably sourced hardwood. The substantial top and carefully proportioned base create a coffee table built for daily use.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'coffee-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT018',
    'Plato Side Table',
    'plato-side-table',
    'MAKEMAKE',
    675,
    'Expertly crafted in our San José workshop, the Plato Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764018674/Plato_Extra_mmupa7.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764018674/Plato_Extra_mmupa7.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328783/Plato2_shzdgj.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328776/Plato_1_evmrsd.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328773/Plato_3_a06y6g.jpg"]'::jsonb,
    '[{"name":"One Size","price":675,"dimensions":"W40 x L40 x H50 cm"}]'::jsonb,
    '[{"label":"Length","value":"40 cm / 15.7\""},{"label":"Width","value":"40 cm / 15.7\""},{"label":"Height","value":"50 cm / 19.7\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Hand-carved from solid Costa Rican hardwood with attention to sculptural detail. Each piece is uniquely shaped and finished.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT007',
    'Poroti Side Table',
    'poroti-side-table',
    'MAKEMAKE',
    565,
    'Expertly crafted in our San José workshop, the Poroti Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328209/Poroti_1_zavffu.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328209/Poroti_1_zavffu.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763328213/Poroti_2_fk4rbm.jpg"]'::jsonb,
    '[{"name":"One Size","price":565,"dimensions":"Ø45 x H48 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"45 cm / 17.7\""},{"label":"Height","value":"48 cm / 18.9\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Hand-turned from solid hardwood with distinctive carved details. Each piece is individually shaped and finished to highlight the wood''s natural character.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'side-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CH005',
    'Rio Chair',
    'rio-chair',
    'MAKEMAKE',
    1130,
    'Expertly crafted in our San José workshop, the Rio Chair embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764010268/Rio1_hfjzx0.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764010268/Rio1_hfjzx0.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764010273/Rio4_m3von5.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764010267/Rio2_p6jfqb.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764010273/Rio4_m3von5.jpg"]'::jsonb,
    '[{"name":"One Size","price":1130,"dimensions":"W78 x D78 x H70 cm (seat H40)"}]'::jsonb,
    '[{"label":"Width","value":"78 cm / 30.7\""},{"label":"Depth","value":"78 cm / 30.7\""},{"label":"Height","value":"70 cm / 27.6\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                         <p><strong>Performance Upholstery:</strong> Exterior-grade fabric designed to resist fading, moisture, and everyday wear. Easy to clean and built for tropical conditions.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Performance upholstery resists moisture and fading.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>                         <p><strong>Machine Wash:</strong> For deeper cleaning, removable covers may be machine washed. Close all zippers, machine wash in cold water on the delicate cycle with mild laundry detergent. Air dry completely"”never tumble dry or apply heat. For severe stains, add 1 cup of color-safe oxygen bleach (such as OxiClean) to the wash cycle"”never use chlorine bleach on colored fabrics.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Crafted with attention to ergonomic form and structural integrity. The curved back and seat are designed for comfortable, extended seating.',
    'all',
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    ARRAY['seating', 'chairs']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'CT001',
    'Ronda Coffee Table',
    'ronda-coffee-table',
    'MAKEMAKE',
    1380,
    'Expertly crafted in our San José workshop, the Ronda Coffee Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160042/Ronda_Coffee_1_pe8z2v.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160042/Ronda_Coffee_1_pe8z2v.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763159984/Ronda_Coffee_2_iaskdr.jpg"]'::jsonb,
    '[{"name":"One Size","price":1380,"dimensions":"W100 x L100 x H40 cm"}]'::jsonb,
    '[{"label":"Length","value":"100 cm / 39.4\""},{"label":"Width","value":"100 cm / 39.4\""},{"label":"Height","value":"40 cm / 15.7\""}]'::jsonb,
    '<p><strong>Local Teak:</strong> Sustainably sourced Costa Rican hardwood with natural resistance to moisture, decay, and insects. Weathers to a silver-grey patina or maintains its golden tone with occasional oiling.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Avoid prolonged direct exposure to rain.</p>',
    '<p>Clean with mild soap and water. Avoid harsh chemicals. Teak naturally silvers over time"”this is normal and does not affect durability. To maintain the original warm tone, apply teak oil 2-3 times per year.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted from sustainably sourced hardwood with a focus on clean lines and honest joinery. The circular top is carefully shaped and finished to highlight the wood''s natural beauty.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'coffee-tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'BT001',
    'Rosario Bistro Table',
    'rosario-bistro-table',
    'MAKEMAKE',
    715,
    'Expertly crafted in our San José workshop, the Rosario Bistro Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '6-8 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160700/Rosario_1_rtf6aw.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160700/Rosario_1_rtf6aw.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160705/Rosario_2_vqmmwo.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763160694/Rosario_3_tvwsw7.jpg"]'::jsonb,
    '[{"name":"One Size","price":715,"dimensions":"Ø60 x H72 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"60 cm / 23.6\""},{"label":"Height","value":"72 cm / 28.3\""}]'::jsonb,
    '<p><strong>GRS (Glass-Reinforced Stone):</strong> A weather-resistant composite of fiberglass, resin, and crushed stone aggregate. UV-stable, and built for outdoor durability"”resists cracking, fading, and moisture damage while maintaining structural integrity through tropical climate extremes.</p>                                                  <p><strong>Indoor/Outdoor Use:</strong> Designed for year-round outdoor use in tropical climates. UV-stable and weather-resistant. Equally striking indoors.</p>',
    '<p><strong>Regular Cleaning:</strong> Clean with mild soap and warm water using a soft cloth or sponge. Rinse thoroughly and allow to air dry.</p>                         <p><strong>Stubborn Stains:</strong> For tougher stains, use a soft brush with mild detergent. Avoid abrasive cleaners or metal brushes that could scratch the surface.</p>                         <p><strong>What to Avoid:</strong> Do not use harsh chemicals, bleach, or acidic cleaners. Avoid pressure washers at close range.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Each Rosario bistro table is crafted by hand in San José using sustainably sourced Costa Rican hardwoods. The wood is carefully selected for grain pattern and character, then shaped and finished with natural oils that enhance its warm tones while protecting the surface.',
    'all',
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    null,
    ARRAY['tables']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'SO009',
    'Sistema Sofa',
    'sistema-sofa',
    'MAKEMAKE',
    0,
    'Expertly crafted in our San José workshop, the Sistema Sofa embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '8-10 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336186/Sistema_Sofa_1_hnysyn.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336186/Sistema_Sofa_1_hnysyn.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1764127442/Sistema_4Seater_r0tbgz_7ae861.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763336250/Sistema_Sofa_2_stivec.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763335641/Sistema_2Seater_csbhos.jpg"]'::jsonb,
    '[{"name":"Single","price":1500,"dimensions":"W110 x D100 x H70 cm (seat H42 cm)"},{"name":"2-Seater","price":2900,"dimensions":"W220 x D100 x H70 cm (seat H42 cm)"},{"name":"3-Seater","price":4450,"dimensions":"W310 x D100 x H70 cm (seat H42 cm)"},{"name":"4-Seater","price":5900,"dimensions":"W400 x D100 x H70 cm (seat H42 cm)"}]'::jsonb,
    '[{"label":"Width","value":"110 cm / 43.3\""},{"label":"Depth","value":"100 cm / 39.4\""},{"label":"Height","value":"70 cm / 27.6\""},{"label":"Width","value":"220 cm / 86.6\""},{"label":"Depth","value":"100 cm / 39.4\""},{"label":"Height","value":"70 cm / 27.6\""},{"label":"Width","value":"310 cm / 122.0\""},{"label":"Depth","value":"100 cm / 39.4\""},{"label":"Height","value":"70 cm / 27.6\""},{"label":"Width","value":"400 cm / 157.5\""},{"label":"Depth","value":"100 cm / 39.4\""},{"label":"Height","value":"70 cm / 27.6\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                         <p><strong>Performance Upholstery:</strong> Exterior-grade fabric designed to resist fading, moisture, and everyday wear. Easy to clean and built for tropical conditions.</p>                                                  <p><strong>Indoor/Covered Outdoor:</strong> Suitable for interior spaces and covered outdoor areas. Performance upholstery resists moisture and fading.</p>',
    '<p>Clean with a soft, dry cloth. For deeper cleaning, use a slightly damp cloth and dry immediately. Avoid exposure to direct sunlight and extreme humidity.</p>                         <p><strong>Machine Wash:</strong> For deeper cleaning, removable covers may be machine washed. Close all zippers, machine wash in cold water on the delicate cycle with mild laundry detergent. Air dry completely"”never tumble dry or apply heat. For severe stains, add 1 cup of color-safe oxygen bleach (such as OxiClean) to the wash cycle"”never use chlorine bleach on colored fabrics.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Professionally upholstered in San José with modular design for flexible configuration. Premium fabrics and solid construction ensure lasting comfort.',
    'all',
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    ARRAY['seating', 'sofas']
);

INSERT INTO products (
    code,
    name,
    slug,
    badge,
    price,
    description,
    lead_time,
    thumbnail_url,
    gallery_images,
    sizes,
    dimensions,
    materials_spec,
    care_instructions,
    shipping_info,
    craftsmanship_title,
    craftsmanship_text,
    material_selection_mode,
    has_local_teak,
    has_semi_satin_lacquer,
    has_white_cement,
    has_metal,
    has_hardwood,
    has_fabric,
    has_leather,
    has_grs,
    materials,
    category
) VALUES (
    'AT028',
    'Winnie Side Table',
    'winnie-side-table',
    'MAKEMAKE',
    515,
    'Expertly crafted in our San José workshop, the Winnie Side Table embodies the perfect balance of contemporary design and traditional craftsmanship. Each piece is made to order, ensuring attention to every detail.',
    '4-6 weeks',
    'https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763337421/Winnie_3_gwfsub.jpg',
    '["https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763337421/Winnie_3_gwfsub.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763337407/Winnie_2_ml5nf9.jpg","https://res.cloudinary.com/duoqn1csd/image/upload/w_1200,f_auto,q_auto/v1763337398/Winnie_4_z8kmjz.jpg"]'::jsonb,
    '[{"name":"One Size","price":515,"dimensions":"Ø42 x H48 cm"}]'::jsonb,
    '[{"label":"Diameter","value":"42 cm / 16.5\""},{"label":"Height","value":"48 cm / 18.9\""}]'::jsonb,
    '<p><strong>Hardwood Finish:</strong> Natural hardwood available in multiple finish options, bringing warmth and organic texture to the design.</p>                         <p><strong>Local Teak:</strong> Sustainably sourced Costa Rican hardwood with natural resistance to moisture, decay, and insects. Weathers to a silver-grey patina or maintains its golden tone with occasional oiling.</p>                                                  <p><strong>Indoor Use:</strong> This piece is designed for interior spaces.</p>',
    '<p>Clean with mild soap and water. Avoid harsh chemicals. Teak naturally silvers over time"”this is normal and does not affect durability. To maintain the original warm tone, apply teak oil 2-3 times per year.</p>',
    '<p>Delivery is available throughout Costa Rica, with shipping costs calculated at checkout based on your location. For international orders, please contact us directly to arrange shipping. Local clients are welcome to collect their purchases at our Escazú warehouse by appointment.</p>',
    'Hand-Crafted in San José',
    'Handcrafted from solid hardwood with attention to detail and finish. Each piece showcases traditional woodworking adapted for contemporary living.',
    'all',
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    ARRAY['tables', 'side-tables']
);
